### ISSUE TITLE
[FEATURE] UTC Clock at AVDGS

### ISSUE THREAD

**Issue by Phil061995** [vACDM/vACDM#9]
Many pilots filed lcl times instead of UTC times. Maybe a clock with the current UTC time somewhere at the website would be helpfull.

Maybe a warning could be added if the TOBT is in the past or to far in the furture.

**Comment by Frenkii** [comment]
Like This?
Example:
![grafik](https://user-images.githubusercontent.com/20613151/233828192-11f68a53-b8d3-4f4f-893e-ca406f966790.png)

**Comment by Phil061995** [comment]
Looks good :)
